### ISSUE TITLE
VP9 reporting support?

### ISSUE THREAD

**Issue by oscarbg** [aaronp24/vdpauinfo#1]
Now that libvdpau 1.3 supports it..
EDIT:
just added and it works..
{"VP9_PROFILE_0", VDP_DECODER_PROFILE_VP9_PROFILE_0},
{"VP9_PROFILE_1", VDP_DECODER_PROFILE_VP9_PROFILE_1},
{"VP9_PROFILE_2", VDP_DECODER_PROFILE_VP9_PROFILE_2},
{"VP9_PROFILE_3", VDP_DECODER_PROFILE_VP9_PROFILE_3},

**Comment by aaronp24** [comment]
Oh sorry, I forgot to make a note here that this project moved to https://gitlab.freedesktop.org/vdpau/vdpauinfo

See https://gitlab.freedesktop.org/vdpau/vdpauinfo/merge_requests/2
